### ISSUE TITLE
Analysis of Gzip vs 7zip

### ISSUE THREAD

**Issue by jessjass** [harvard-lts/epadd#123]
In order to zip epadd exports for ingest into DRS, the choice of using 7zip vs Gzip must be decided

**Comment by awoods** [comment]
In agreement with @mztrz 's analysis, 7-zip appears to be an excellent option for the CuratorApp to use in aggregating and compressing the export of ePADD.

The driving need that motivated finding an aggregation format other than Zip is the limitation of Zip's size to 4GB. On the other hand, 7-zip has the much larger maximum file size of 16,000PB:
https://7-zip.org/7z.html

Other factors of consideration include: memory usage, compression time, compression ratio, preservation characteristics.

Since the CuratorApp and other utility apps will not be working in a memory-constrained environment and compression times of the various formats are comparable within an order of magnitude, the most important considerations are compression ratio and preservation characteristics. 

The following analysis rates 7-zip very highly with compression ratio across a range of file collection types:
https://bewilderedoctothorpe.net/2019/02/08/compression-comparison-archive-formats/

Regarding preservation, 7zip is an open format that includes internal CRC values and documented approaches for corruption recovery:
https://www.7-zip.org/recover.html

Additionally, it is reassuring that 7-zip is used by the Library of Congress:
https://www.loc.gov/preservation/digital/formats/fdd/fdd000539.shtml#local

Unlike 7-zip which is both an [archive](https://en.wikipedia.org/wiki/Archive_file) and compression format, Gzip is only a compression format. This means that in order to consider Gzip, it would be combined with an archive format such as Tar. As seen in the previously referenced compression tests, 7-zip performs better than Gzip/Tar.

**Comment by jessjass** [comment]
We are going to be using 7zip
