### ISSUE TITLE
Investigate exporting HUA content out of EAS

### ISSUE THREAD

**Issue by ives1227** [harvard-lts/epadd#19]
As an HUA curator, I would like to extract the content I have in EAS in mbox format for easy import into ePADD.

Do we have the original packets?  These may be best to use to convert to mbox.

Test Emailchemy to see if we can convert original packets to mbox.

**Comment by ives1227** [comment]
Dee Dee TODO:
1. Export eml from EAS for Julie to test.
2. Does EAS keep the original packets?

**Comment by ives1227** [comment]
@juliewetherill iI sent you a sample via SharePoint of something HUA has. 

It looks like EAS does keep the original format based on what I've seen.  It has the original and then a 'converted' directory.

**Comment by juliewetherill** [comment]
I got the HUA mbox sample. Is the next step to have epadd ingest it? The story doesn't say what's needed.

**Comment by awoods** [comment]
@juliewetherill : Since you have the HUA/EAS mbox, ingesting it into ePADD will help us advise the HUA curators on how to handle their content that is currently in EAS. It would likely be useful to get @mztrz and/or the curator's review of what the content looks like in ePADD.

**Comment by awoods** [comment]
@juliewetherill : Based on team discussion on 2022-09-20, it was decided to just put the mbox files in a shared dropbox for HUA. If necessary, we may need to convert what we extract from EAS into mbox.

**Comment by mztrz** [comment]
Update: Skip would like us to export the following packets - in BOTH the original format/packet and a converted mbox file version if applicable - to a secure drop box:

**10 packets**
- Three that have Crimson in the title
- Rebecca Graham
- William Graham
- Cherry Murray
- Jan Merrill-Oldham
- Francis Clooney
- Randy Stern
- Tracey Robinson

**Comment by awoods** [comment]
@mztrz : who is in a position to export the 10 packets?

Edit: pending @ives1227 's return: end of Oct.

**Comment by mztrz** [comment]
Here is a new message from Abby in the Art Museum - they do need one packet from EAS exported back to them:

I did actually find one that I think I’ll need extracted from EAS. We do have a backup (two, in fact) of the original file, but Emailchemy can’t seem to parse it (either copy). It’s a PST, but it seems to be corrupt. However, EAS was able to ingest it, so I’d like to try to get a usable copy from there. It is packet ID 1442, packet name HUAM_RECORDS_2018_78_kopp. Please let me know if there is more information you need from me in order to retrieve it. Whatever format can be exported will be fine – I can convert again as necessary as long as I have the emails themselves.

**Comment by awoods** [comment]
Next steps: export the 10 (HUA) and one (HAM) packets from EAS. @ives1227 can do this; others?
- Exports: original and mbox

**Comment by awoods** [comment]
Follow-on action: #121
