### ISSUE TITLE
Follow-up with HAM and HUA on unsubmitted content

### ISSUE THREAD

**Issue by awoods** [harvard-lts/epadd#42]
As an EAS product owner, I want to know how the current owner codes want to handle the content in the EAS dropboxes before those storage nodes get decommissioned. The result of the conversation should:

1. Determine where each item should be migrated (DRS or ePADD)
2. Where should the metadata attached to the items should be mapped to the destination (DRS/ePADD)

**Comment by ives1227** [comment]
Tricia will be out for week 1 of this sprint but will complete it in week 2

**Comment by mztrz** [comment]
Abby/HAM response: 
Thanks for reaching out about our EAS content. In answer to your questions:

 

No, none of this material is ready for deposit to the DRS.
We do have local copies of the email accounts, and we have conversion software.
We do not need records extracted and transferred to us; although we will lose some weeding we have already done in those accounts, recreating that work in ePADD is so easy and fast that it doesn’t feel worth it to us to try to salvage what’s in EAS.
 

So in short, we intend to abandon the data in EAS when we transition to ePADD. However, as you know, we are currently unable to use ePADD due to the known “exception fetching/indexing emails” bug. You said in your email that you’ll launch “full support of ePADD” at the end of the year; does this mean that you anticipate the “exception…” bug will be resolved by then? If so, we will be delighted to shift our workflow (and data) entirely to ePADD! (Truly, we cannot wait!) If not, though, decommissioning EAS before we have a viable alternative seems precipitous.

 

As you know, our recent use of EAS has been very minimal (we haven’t ingested anything new into EAS in years, but we do still occasionally access what’s already there), and we have determined some workarounds for accessing email that is neither in EAS nor ePADD. However, we are reluctant to lose access to the EAS content until we are able to ingest those same accounts into ePADD. I know there are challenges to finding the resources to troubleshoot the bug, but I sincerely hope it will be resolved before EAS is decommissioned.

**Comment by mztrz** [comment]
Skip/HUA response: 
In our recordkeeping, I count 10 packets (not sure of the exact names of the packets):

Three that have Crimson in the title
Rebecca Graham
William Graham
Cherry Murray
Jan Merrill-Oldham
Francis Clooney
Randy Stern
Tracey Robinson

I have those totaling 39633.37 MB.

I’m not sure how to account for the difference between your numbers and mine.

We’ve had one packet go all the way through to DRS: Lawrence Bogorad. I wonder if it’s still in EAS due to cleanup not happening.

We did have a number of failed deposit attempts. I wonder if those left traces in the system?

None of these packets are currently ready for DRS, so that much is off the table. Of the eight collections above, only the Crimson packets were not Outlook email, so while I think we have copies of the Outlook packets on this end, we’d have to convert them again to work with them in ePADD. Consequently, it seems like it’d be more efficient to extract them from EAS as mbox.

If  you want to send me a list of the packet names, I can go over them to see if I can figure out why our numbers are so different.
