### ISSUE TITLE
BatchBuilder MediaInfo error in Linux

### ISSUE THREAD

**Issue by juliewetherill** [harvard-lts/epadd#49]
See https://jira.huit.harvard.edu/browse/LIBDRS-8788

**Comment by ives1227** [comment]
Paul A is on vacation this week.  Need more info to replicate.  Will look at this again on Monday the 25th

**Comment by ives1227** [comment]
New directory is /drs2qa/test-deposit-staging/

**Comment by ives1227** [comment]
Paul A was testing from the /drs2qa mount which may be the problem.  I can run BB from my home directory and it is fine, running it from the /drs2qa mount fails the same as his.  He will be putting BB in his home directory and testing from there.

**Comment by ives1227** [comment]
Testing from the /drs2qa mount seemed to be the problem. Since /drs2qa is a mount and likely doesn't have permissions to run certain executables, I suspect that was the problem.  Batch Builder should not be placed directly on a DRS FS mount.  

BB runs fine when run from the user's home directory on doyle.
